FROM golang:1.15.0 as builder

WORKDIR /go/src/github.com/fatedier/frp/

COPY . .
RUN go get ./...
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./bin/frps ./cmd/frps
RUN chmod -R 777 ./bin/frps

FROM alpine:latest

WORKDIR /app
COPY --from=builder /go/src/github.com/fatedier/frp/bin/frps /usr/bin

ENTRYPOINT ["/usr/bin/frps"]
